# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_photo_embeddings"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="caption_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="caption_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="caption_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="photo",
            name="caption_tokens",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
