# Generated by Codex on 2026-03-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import web.models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_photo_captions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="people", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DetectedFace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preview_image", models.FileField(blank=True, max_length=500, upload_to=web.models.user_face_preview_upload_to)),
                ("bbox", models.JSONField(blank=True, default=list)),
                ("landmarks", models.JSONField(blank=True, default=list)),
                ("detection_score", models.FloatField(default=0.0)),
                ("quality_score", models.FloatField(default=0.0)),
                ("embedding_model", models.CharField(blank=True, max_length=120)),
                ("embedding_dimension", models.PositiveIntegerField(default=0)),
                ("embedding_vector", models.JSONField(blank=True, default=list)),
                ("embedding_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="faces", to="web.person"),
                ),
                (
                    "photo",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="detected_faces", to="web.photo"),
                ),
            ],
            options={
                "ordering": ["-quality_score", "id"],
            },
        ),
    ]
