# Generated by Codex on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="embedding_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="embedding_dimension",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="photo",
            name="embedding_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="photo",
            name="embedding_pretrained_tag",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="photo",
            name="embedding_vector",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
