# Generated by Codex on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_people_and_faces"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="caption_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="caption_ru_synonyms",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
