# Generated by Django 5.2.12 on 2026-03-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_telegramprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='entity_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='photo',
            name='search_synonyms_ru',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='search_terms_en',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='search_terms_ru',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
